- name: reload nginx
  service:
    name: nginx
    state: restarted

- name: restart mysql
  service: 
    name: mysql
    state: restarted

- name: flush-privileges
  command: mysqladmin flush-privileges