- name: Import database
  hosts: "{{ host }}"

  tasks:

  - pause:
      prompt: "WARNING: RUNNING ON PROD"
    when: host == "prod"

  - name: Copy file
    copy:
      src: "{{ file }}"
      dest: /tmp

  - name: Backup database
    mysql_db:
      state: dump
      name: "{{ omskvelo_sql_db }}"
      target: "/tmp/{{ inventory_hostname }}-{{ ansible_date_time.iso8601_basic }}.sql"
      login_user: "{{ omskvelo_sql_user }}"
      login_password: "{{ omskvelo_sql_password }}"

  - name: Delete database
    mysql_db:
      state: absent
      name: "{{ omskvelo_sql_db }}"
      login_user: "{{ omskvelo_sql_user }}"
      login_password: "{{ omskvelo_sql_password }}"

  - name: Create database
    mysql_db:
      state: present
      name: "{{ omskvelo_sql_db }}"
      login_user: "{{ omskvelo_sql_user }}"
      login_password: "{{ omskvelo_sql_password }}"

  - name: Import database
    mysql_db:
      name: "{{ omskvelo_sql_db }}"
      state: import
      target: "/tmp/{{ file }}"
      login_user: "{{ omskvelo_sql_user }}"
      login_password: "{{ omskvelo_sql_password }}"
  
  - name: Remove tmp file
    file:
      state: absent
      path: "/tmp/{{ file }}"
