- name: Deploy Invision Community Suite sources
  hosts: "{{ host }}"
  vars:
    - dump_file_name: "{{ inventory_hostname }}-ipb-{{ ansible_date_time.iso8601_basic_short }}"

  tasks:

  - name: git clone locally
    local_action:
      module: git
      repo: "git@bitbucket.org:ivanzoid/omskvelo-forum.git"
      dest: "omskvelo-forum"
      depth: 1

  - name: remove .git locally
    local_action:
      module: file
      path: "omskvelo-forum/.git"
      state: absent

  - name: make backup 
    archive:
      path: "{{ ipb_location }}"
      dest: "/tmp/{{ dump_file_name }}.tgz"
    become: yes

  - name: remove dir
    file:
      path: "{{ ipb_location }}"
      state: absent
    become: yes

  - name: create dir
    file:
      path: "{{ ipb_location }}"
      state: directory
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
    become: yes

  - name: copy sources
    synchronize:
      src: omskvelo-forum/
      dest: "{{ ipb_location }}"

  - name: remove sources locally
    local_action:
      module: file
      path: "omskvelo-forum"
      state: absent

  - name: update dir permissions
    file:
      path: "{{ forum_location }}"
      state: directory
      recurse: yes
      owner: "{{ omskvelo_unix_user }}"
      group: "{{ omskvelo_unix_group }}"
    become: yes

  - name: update other dir permissions
    file:
      path: '{{ item }}'
      state: directory
      owner: "{{ omskvelo_unix_user }}"
      group: "{{ omskvelo_unix_group }}"
      mode: 0770
    with_items:
      - "{{ forum_location }}/datastore"
      - "{{ forum_location }}/uploads"
      - "{{ forum_location }}/uploads/logs"
      - "{{ ipb_location }}/plugins"
    become: yes

  - name: Link IPB configuration
    file:
      src: "../conf_global.php"
      dest: "{{ ipb_location }}/conf_global.php"
      state: link
