php_enable_php_fpm: true
php_webserver_daemon: nginx

php_packages_extra:
  - php{{php_version}}-mbstring
  - php{{php_version}}-xml
  - php{{php_version}}-zip
  - php{{php_version}}-memcached
  - php{{php_version}}-mysqli
  - php{{php_version}}-imagick
  