- name: Copy IPB configuration
  template:
    src: "templates/{{ item }}"
    dest: "{{ forum_location }}/{{ item }}"
    mode: '444'
    owner: "{{ omskvelo_unix_user }}"
    group: "{{ omskvelo_unix_group }}"
  with_items: "{{ ipb_config_files }}"

- name: Stat IPB dir
  stat:
    path: "{{ ipb_location }}"
  register: ipb_dir_stat

- name: Link IPB configuration
  file:
    src: "../{{ item }}"
    dest: "{{ ipb_location }}/{{ item }}"
    state: link
  with_items: "{{ ipb_config_files }}"
  when: ipb_dir_stat.stat.exists
