- name: Create omskvelo unix group
  group: 
    name: "{{ omskvelo_unix_group }}"
    state: present

- name: Create omskvelo unix user
  user:
    name: "{{ omskvelo_unix_user }}"
    group: "{{ omskvelo_unix_group }}"
    shell: /usr/sbin/nologin
    createhome: no
    state: present

- name: Ensure a locale exists
  locale_gen:
    name: ru_RU.UTF-8
    state: present

- name: Ensure a locale exists
  locale_gen:
    name: ru_RU
    state: present